name: rayhan_test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_secure_storage: ^1.0.5
  get: ^4.7.2
  flutter_spinkit: ^5.2.1
  pinput:
  google_fonts: ^6.3.2
  dio:
  logger: ^2.0.2
  intl:
  flutter_svg:
  cached_network_image: ^3.4.1
  font_awesome_flutter: ^10.8.0
  carousel_slider:
  flutter_staggered_grid_view: ^0.7.0
  sqflite: ^2.4.2
  path: ^1.9.1
  image_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.7

# -----------------------------
# ğŸš€ Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª Ø´Ø§Ø´Ø© Ø§Ù„Ø³Ø¨Ù„Ø§ØªØ´
# -----------------------------
flutter_native_splash:
  android: true
  ios: true
  web: false

  # Ø§Ù„Ø®Ù„ÙÙŠØ©
  color: "#FFFFFF"

  # Ø§Ù„Ù„ÙˆØ¬Ùˆ
  image: assets/images/logo_start.png

  ios_content_mode: scaleAspectFit

  # Ø§Ù„ÙˆØ¶Ø¹ Ø§Ù„Ø¯Ø§ÙƒÙ†
  color_dark: "#FFFFFF"
  image_dark: assets/images/logo_android12_ready.png

  android_12:
    image: assets/images/logo_android12_ready.png
    image_dark: assets/images/logo_android12_ready.png
    # icon_background_color: "#FFFFFF"
    # icon_background_color_dark: "#FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/images/